name: Update Version

on:
    pull_request:
        types: [closed]
        branches:
            - main
            - master

jobs:
    bump-version:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: pip install tomli tomli-w

            - name: Update version
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  python bump_version.py

            - name: Push changes
              run: git push
